resources:
  - name: aoc-std
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc-std.git
      ignore_paths:
        - 'README.md'
jobs:
  - name: lint-and-test
    build_log_retention:
      builds: 50
    plan:
      - get: aoc-std
        trigger: true
      - task: test-and-bench
        tags:
          - internal
        file: aoc-std/ci/test.yaml
        input_mapping:
          repo: aoc-std
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((registry-index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((registry-token))
